// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: jobscheduler/worker/v1/worker.proto

// Worker protocol between workers and engine nodes (LLD §12.1). Fields are only ever added;
// a breaking change means a v2 package served side by side.

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_OUTCOME_SUCCEEDED   Outcome = 1
	Outcome_OUTCOME_FAILED      Outcome = 2
	Outcome_OUTCOME_TIMED_OUT   Outcome = 3
	Outcome_OUTCOME_CANCELLED   Outcome = 4
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUCCEEDED",
		2: "OUTCOME_FAILED",
		3: "OUTCOME_TIMED_OUT",
		4: "OUTCOME_CANCELLED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUCCEEDED":   1,
		"OUTCOME_FAILED":      2,
		"OUTCOME_TIMED_OUT":   3,
		"OUTCOME_CANCELLED":   4,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_jobscheduler_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_jobscheduler_worker_v1_worker_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pool  string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	// Job types this worker can run; empty means every type in the pool.
	JobTypes []string          `protobuf:"bytes,2,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	Slots    int32             `protobuf:"varint,3,opt,name=slots,proto3" json:"slots,omitempty"`
	Labels   map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Identifies the process to operators, e.g. host and PID.
	WorkerId       string `protobuf:"bytes,5,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RuntimeVersion string `protobuf:"bytes,6,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *RegisterRequest) GetJobTypes() []string {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *RegisterRequest) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LeaseTtl          *durationpb.Duration   `protobuf:"bytes,2,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

func (x *RegisterResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

type PollRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaxJobs   int32                  `protobuf:"varint,2,opt,name=max_jobs,json=maxJobs,proto3" json:"max_jobs,omitempty"`
	// How long to wait for work; the server caps it at 30 s.
	Wait          *durationpb.Duration `protobuf:"bytes,3,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PollRequest) GetMaxJobs() int32 {
	if x != nil {
		return x.MaxJobs
	}
	return 0
}

func (x *PollRequest) GetWait() *durationpb.Duration {
	if x != nil {
		return x.Wait
	}
	return nil
}

type PollResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Assignments []*Assignment          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	// Poll the pool owner at this address instead.
	RedirectAddress string `protobuf:"bytes,2,opt,name=redirect_address,json=redirectAddress,proto3" json:"redirect_address,omitempty"`
	// The pool has no owner yet; poll again after this delay.
	RetryAfter *durationpb.Duration `protobuf:"bytes,3,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	// An operator asked this worker to drain: stop polling, finish running jobs, deregister.
	Drain         bool `protobuf:"varint,4,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PollResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *PollResponse) GetRedirectAddress() string {
	if x != nil {
		return x.RedirectAddress
	}
	return ""
}

func (x *PollResponse) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *PollResponse) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job ID is also the handler's idempotency key.
	JobId     string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId string `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	// The attempt number is the fencing token.
	AttemptNumber  int64  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	JobType        string `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	JobTypeVersion int32  `protobuf:"varint,5,opt,name=job_type_version,json=jobTypeVersion,proto3" json:"job_type_version,omitempty"`
	// JSON.
	Payload  []byte            `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Labels   map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantId string            `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Priority string            `protobuf:"bytes,9,opt,name=priority,proto3" json:"priority,omitempty"`
	// The attempt deadline on the database clock, for information.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// The attempt timeout, which the worker enforces from receipt on its monotonic clock.
	Timeout       *durationpb.Duration   `protobuf:"bytes,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,12,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	FireTime      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=fire_time,json=fireTime,proto3" json:"fire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Assignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Assignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Assignment) GetAttemptNumber() int64 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *Assignment) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Assignment) GetJobTypeVersion() int32 {
	if x != nil {
		return x.JobTypeVersion
	}
	return 0
}

func (x *Assignment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Assignment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Assignment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Assignment) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Assignment) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Assignment) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Assignment) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Assignment) GetFireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FireTime
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Running       []*RunningAttempt      `protobuf:"bytes,2,rep,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunning() []*RunningAttempt {
	if x != nil {
		return x.Running
	}
	return nil
}

type RunningAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AttemptNumber int64                  `protobuf:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningAttempt) Reset() {
	*x = RunningAttempt{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningAttempt) ProtoMessage() {}

func (x *RunningAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningAttempt.ProtoReflect.Descriptor instead.
func (*RunningAttempt) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *RunningAttempt) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunningAttempt) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RunningAttempt) GetAttemptNumber() int64 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attempts whose job was cancelled: cancel the handler and report OUTCOME_CANCELLED.
	Cancel []string `protobuf:"bytes,1,rep,name=cancel,proto3" json:"cancel,omitempty"`
	// Attempts that are no longer current: stop them and drop their results.
	Stale []string `protobuf:"bytes,2,rep,name=stale,proto3" json:"stale,omitempty"`
	// An operator asked this worker to drain: stop polling, finish running jobs, deregister.
	Drain         bool `protobuf:"varint,3,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetCancel() []string {
	if x != nil {
		return x.Cancel
	}
	return nil
}

func (x *HeartbeatResponse) GetStale() []string {
	if x != nil {
		return x.Stale
	}
	return nil
}

func (x *HeartbeatResponse) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	AttemptNumber int64                  `protobuf:"varint,4,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Outcome       Outcome                `protobuf:"varint,5,opt,name=outcome,proto3,enum=jobscheduler.worker.v1.Outcome" json:"outcome,omitempty"`
	// For OUTCOME_FAILED: whether the job may be retried.
	Retryable bool `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// For retryable failures: the handler's suggested delay before the next attempt.
	RetryAfter *durationpb.Duration `protobuf:"bytes,7,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	Error      string               `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// For OUTCOME_SUCCEEDED: an optional JSON result.
	Result        []byte `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *CompleteRequest) GetAttemptNumber() int64 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *CompleteRequest) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *CompleteRequest) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *CompleteRequest) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *CompleteRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompleteRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job's state after the report.
	JobState string `protobuf:"bytes,1,opt,name=job_state,json=jobState,proto3" json:"job_state,omitempty"`
	// The report repeated one already recorded.
	Replayed      bool `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteResponse) GetJobState() string {
	if x != nil {
		return x.JobState
	}
	return ""
}

func (x *CompleteResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *DeregisterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jobscheduler_worker_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_jobscheduler_worker_v1_worker_proto_rawDescGZIP(), []int{11}
}

var File_jobscheduler_worker_v1_worker_proto protoreflect.FileDescriptor

const file_jobscheduler_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"#jobscheduler/worker/v1/worker.proto\x12\x16jobscheduler.worker.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x02\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x1b\n" +
	"\tjob_types\x18\x02 \x03(\tR\bjobTypes\x12\x14\n" +
	"\x05slots\x18\x03 \x01(\x05R\x05slots\x12K\n" +
	"\x06labels\x18\x04 \x03(\v23.jobscheduler.worker.v1.RegisterRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tworker_id\x18\x05 \x01(\tR\bworkerId\x12'\n" +
	"\x0fruntime_version\x18\x06 \x01(\tR\x0eruntimeVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\tlease_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\x12H\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"v\n" +
	"\vPollRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmax_jobs\x18\x02 \x01(\x05R\amaxJobs\x12-\n" +
	"\x04wait\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x04wait\"\xd1\x01\n" +
	"\fPollResponse\x12D\n" +
	"\vassignments\x18\x01 \x03(\v2\".jobscheduler.worker.v1.AssignmentR\vassignments\x12)\n" +
	"\x10redirect_address\x18\x02 \x01(\tR\x0fredirectAddress\x12:\n" +
	"\vretry_after\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x12\x14\n" +
	"\x05drain\x18\x04 \x01(\bR\x05drain\"\xcb\x04\n" +
	"\n" +
	"Assignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x03R\rattemptNumber\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12(\n" +
	"\x10job_type_version\x18\x05 \x01(\x05R\x0ejobTypeVersion\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12F\n" +
	"\x06labels\x18\a \x03(\v2..jobscheduler.worker.v1.Assignment.LabelsEntryR\x06labels\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x1a\n" +
	"\bpriority\x18\t \x01(\tR\bpriority\x126\n" +
	"\bdeadline\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x123\n" +
	"\atimeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\vschedule_id\x18\f \x01(\tR\n" +
	"scheduleId\x127\n" +
	"\tfire_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bfireTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\arunning\x18\x02 \x03(\v2&.jobscheduler.worker.v1.RunningAttemptR\arunning\"m\n" +
	"\x0eRunningAttempt\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12%\n" +
	"\x0eattempt_number\x18\x03 \x01(\x03R\rattemptNumber\"W\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06cancel\x18\x01 \x03(\tR\x06cancel\x12\x14\n" +
	"\x05stale\x18\x02 \x03(\tR\x05stale\x12\x14\n" +
	"\x05drain\x18\x03 \x01(\bR\x05drain\"\xd0\x02\n" +
	"\x0fCompleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12%\n" +
	"\x0eattempt_number\x18\x04 \x01(\x03R\rattemptNumber\x129\n" +
	"\aoutcome\x18\x05 \x01(\x0e2\x1f.jobscheduler.worker.v1.OutcomeR\aoutcome\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x12:\n" +
	"\vretry_after\x18\a \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\t \x01(\fR\x06result\"K\n" +
	"\x10CompleteResponse\x12\x1b\n" +
	"\tjob_state\x18\x01 \x01(\tR\bjobState\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\"2\n" +
	"\x11DeregisterRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x14\n" +
	"\x12DeregisterResponse*{\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTCOME_SUCCEEDED\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x02\x12\x15\n" +
	"\x11OUTCOME_TIMED_OUT\x10\x03\x12\x15\n" +
	"\x11OUTCOME_CANCELLED\x10\x042\xe7\x03\n" +
	"\rWorkerService\x12]\n" +
	"\bRegister\x12'.jobscheduler.worker.v1.RegisterRequest\x1a(.jobscheduler.worker.v1.RegisterResponse\x12Q\n" +
	"\x04Poll\x12#.jobscheduler.worker.v1.PollRequest\x1a$.jobscheduler.worker.v1.PollResponse\x12`\n" +
	"\tHeartbeat\x12(.jobscheduler.worker.v1.HeartbeatRequest\x1a).jobscheduler.worker.v1.HeartbeatResponse\x12]\n" +
	"\bComplete\x12'.jobscheduler.worker.v1.CompleteRequest\x1a(.jobscheduler.worker.v1.CompleteResponse\x12c\n" +
	"\n" +
	"Deregister\x12).jobscheduler.worker.v1.DeregisterRequest\x1a*.jobscheduler.worker.v1.DeregisterResponseB$Z\"jobscheduler/pkg/workerpb;workerpbb\x06proto3"

var (
	file_jobscheduler_worker_v1_worker_proto_rawDescOnce sync.Once
	file_jobscheduler_worker_v1_worker_proto_rawDescData []byte
)

func file_jobscheduler_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_jobscheduler_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_jobscheduler_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobscheduler_worker_v1_worker_proto_rawDesc), len(file_jobscheduler_worker_v1_worker_proto_rawDesc)))
	})
	return file_jobscheduler_worker_v1_worker_proto_rawDescData
}

var file_jobscheduler_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobscheduler_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_jobscheduler_worker_v1_worker_proto_goTypes = []any{
	(Outcome)(0),                  // 0: jobscheduler.worker.v1.Outcome
	(*RegisterRequest)(nil),       // 1: jobscheduler.worker.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: jobscheduler.worker.v1.RegisterResponse
	(*PollRequest)(nil),           // 3: jobscheduler.worker.v1.PollRequest
	(*PollResponse)(nil),          // 4: jobscheduler.worker.v1.PollResponse
	(*Assignment)(nil),            // 5: jobscheduler.worker.v1.Assignment
	(*HeartbeatRequest)(nil),      // 6: jobscheduler.worker.v1.HeartbeatRequest
	(*RunningAttempt)(nil),        // 7: jobscheduler.worker.v1.RunningAttempt
	(*HeartbeatResponse)(nil),     // 8: jobscheduler.worker.v1.HeartbeatResponse
	(*CompleteRequest)(nil),       // 9: jobscheduler.worker.v1.CompleteRequest
	(*CompleteResponse)(nil),      // 10: jobscheduler.worker.v1.CompleteResponse
	(*DeregisterRequest)(nil),     // 11: jobscheduler.worker.v1.DeregisterRequest
	(*DeregisterResponse)(nil),    // 12: jobscheduler.worker.v1.DeregisterResponse
	nil,                           // 13: jobscheduler.worker.v1.RegisterRequest.LabelsEntry
	nil,                           // 14: jobscheduler.worker.v1.Assignment.LabelsEntry
	(*durationpb.Duration)(nil),   // 15: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_jobscheduler_worker_v1_worker_proto_depIdxs = []int32{
	13, // 0: jobscheduler.worker.v1.RegisterRequest.labels:type_name -> jobscheduler.worker.v1.RegisterRequest.LabelsEntry
	15, // 1: jobscheduler.worker.v1.RegisterResponse.lease_ttl:type_name -> google.protobuf.Duration
	15, // 2: jobscheduler.worker.v1.RegisterResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	15, // 3: jobscheduler.worker.v1.PollRequest.wait:type_name -> google.protobuf.Duration
	5,  // 4: jobscheduler.worker.v1.PollResponse.assignments:type_name -> jobscheduler.worker.v1.Assignment
	15, // 5: jobscheduler.worker.v1.PollResponse.retry_after:type_name -> google.protobuf.Duration
	14, // 6: jobscheduler.worker.v1.Assignment.labels:type_name -> jobscheduler.worker.v1.Assignment.LabelsEntry
	16, // 7: jobscheduler.worker.v1.Assignment.deadline:type_name -> google.protobuf.Timestamp
	15, // 8: jobscheduler.worker.v1.Assignment.timeout:type_name -> google.protobuf.Duration
	16, // 9: jobscheduler.worker.v1.Assignment.fire_time:type_name -> google.protobuf.Timestamp
	7,  // 10: jobscheduler.worker.v1.HeartbeatRequest.running:type_name -> jobscheduler.worker.v1.RunningAttempt
	0,  // 11: jobscheduler.worker.v1.CompleteRequest.outcome:type_name -> jobscheduler.worker.v1.Outcome
	15, // 12: jobscheduler.worker.v1.CompleteRequest.retry_after:type_name -> google.protobuf.Duration
	1,  // 13: jobscheduler.worker.v1.WorkerService.Register:input_type -> jobscheduler.worker.v1.RegisterRequest
	3,  // 14: jobscheduler.worker.v1.WorkerService.Poll:input_type -> jobscheduler.worker.v1.PollRequest
	6,  // 15: jobscheduler.worker.v1.WorkerService.Heartbeat:input_type -> jobscheduler.worker.v1.HeartbeatRequest
	9,  // 16: jobscheduler.worker.v1.WorkerService.Complete:input_type -> jobscheduler.worker.v1.CompleteRequest
	11, // 17: jobscheduler.worker.v1.WorkerService.Deregister:input_type -> jobscheduler.worker.v1.DeregisterRequest
	2,  // 18: jobscheduler.worker.v1.WorkerService.Register:output_type -> jobscheduler.worker.v1.RegisterResponse
	4,  // 19: jobscheduler.worker.v1.WorkerService.Poll:output_type -> jobscheduler.worker.v1.PollResponse
	8,  // 20: jobscheduler.worker.v1.WorkerService.Heartbeat:output_type -> jobscheduler.worker.v1.HeartbeatResponse
	10, // 21: jobscheduler.worker.v1.WorkerService.Complete:output_type -> jobscheduler.worker.v1.CompleteResponse
	12, // 22: jobscheduler.worker.v1.WorkerService.Deregister:output_type -> jobscheduler.worker.v1.DeregisterResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_jobscheduler_worker_v1_worker_proto_init() }
func file_jobscheduler_worker_v1_worker_proto_init() {
	if File_jobscheduler_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobscheduler_worker_v1_worker_proto_rawDesc), len(file_jobscheduler_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobscheduler_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_jobscheduler_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_jobscheduler_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_jobscheduler_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_jobscheduler_worker_v1_worker_proto = out.File
	file_jobscheduler_worker_v1_worker_proto_goTypes = nil
	file_jobscheduler_worker_v1_worker_proto_depIdxs = nil
}
